algoritmo "exercício_2"

var
a,b,c,d: real
inicio
escreva("Digite o primeiro número: ")
leia(a)
escreva("Digite o segundo número: ")
leia(b)
escreva("Digite o terceiro número: ")
leia(c)
escreva("Digite o quarto número: ")
leia(d)
a <- exp(a, 2)
b <- exp(b, 2)
c <- exp(c, 2)
d <- exp(d, 2)
se c >= 1000 entao
 escreval(c)
 escreva("Programa finalizado")
senao entao
 escreval(a)
 escreval(b)
 escreval(c)
 escreval(d)
 escreval("Programa finalizado")
fimse
fimalgoritmo
