algoritmo "exercício_4"

var
senha: caractere
nome: caractere
inicio
escreval("Cadastro de nome de usuário e senha")
enquanto nome = senha faca
 escreva("Digite seu nome de usuário: ")
 leia(nome)
 escreva("Digite sua senha: ")
 leia(senha)
 se senha = nome entao
  escreval("A senha não pode ser igual ao nome de usuário")
  escreval("Por favor digite novamente")
  escreval()
 fimse
fimenquanto
escreval("Cadastro feito com sucesso !")
fimalgoritmo
